<?php

/**
 * @file
 * Contains dckyiv_user module functionality.
 */

use Drupal\dckyiv_user\Form\DCKUserRegisterForm;

/**
 * Implements hook_entity_type_build().
 */
function dckyiv_user_entity_type_build(array &$entity_types) {
  // Map the Project Form view mode to the class who handle that view mode.
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['user'])) {
    $entity_types['user']
      ->setFormClass('register', DCKUserRegisterForm::class);

  }
}

/**
 * Implements hook_mail_alter().
 */
function dckyiv_user_mail_alter(&$message) {
  // Set html type.
  $use_html = FALSE;
  foreach ($message['body'] as $item) {
    if ($item != strip_tags($item)) {
      $use_html = TRUE;
      continue;
    }
  }

  if ($use_html) {
    $message['headers']['Content-Type'] = 'text/html';
  }
}
