<?php

use Drupal\dckyiv_user\Form\DCKUserRegisterForm;

/**
 * Implements hook_entity_type_build().
 */
function dckyiv_user_entity_type_build(array &$entity_types) {
  // Map the Project Form view mode to the class who handle that view mode.
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['user'])) {
    $entity_types['user']
      ->setFormClass('register', DCKUserRegisterForm::class);

  }
}

/**
 * Implements hook_mail_alter().
 */
function dckyiv_user_mail_alter(&$message) {
  // Set html type.
  $use_html = FALSE;
  foreach ($message['body'] as $item) {
    if ($item != strip_tags($item)) {
      $use_html = TRUE;
      continue;
    }
  }

  if ($use_html) {
    $message['headers']['Content-Type'] = 'text/html';
  }
}

/*function dckyiv_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  kint($form_id);
}*/

/**
 * Implements HOOK_form_form_id_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function dckyiv_form_webform_submission_contact_add_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  //$form['elements']['first_and_last_name']['#autocomplete_route_name'] = 'dckyiv_user.autocomplete';
  //$form['elements']['first_and_last_name']['#autocomplete_route_parameters'] = ['field_name' => 'name', 'count' => 10];
/*kint($form['elements']['first_and_last_name']);
kint($form['elements']['autocomplete']);
  $form['elements']['autocomplete']['#autocomplete_route_name'] = 'dckyiv_user.autocomplete';
  $form['elements']['autocomplete']['#autocomplete_route_parameters'] = ['field_user_first_name' => 'name', 'count' => 10];*/
}
