<?php

/**
 * @file
 * Contains dckyiv_core.module.
 */

use Drupal\dckyiv_core\PreprocessTransparentMenu;

/**
 * Implements hook_preprocess_HOOK().
 */
function dckyiv_core_preprocess_html(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(PreprocessTransparentMenu::class)
    ->preprocessHtml($variables);
}

/**
 * Implements hook_entity_type_alter().
 */
function dckyiv_core_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type)
  {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}

/**
 * Implements hook_form_alter().
 */
function dckyiv_core_form_alter(&$form, &$form_state, $form_id) {
  // Override revision form in presentation form.
  if ($form_id === 'node_presentation_form') {
    $form["revision_information"]["#title"] = t('Message to org team:');
    $form["revision_log"]["widget"][0]['value']["#title"] = FALSE;
    $form["revision_log"]["widget"][0]['value']["#description"] = t('If you have any comments to org team, write them here.');
  }
}
