<?php

/**
 * @file
 * Contains dckyiv_core.module.
 */

use Drupal\dckyiv_core\PreprocessTransparentMenu;

/**
 * Implements hook_preprocess_HOOK().
 */
function dckyiv_core_preprocess_html(&$variables) {
  \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(PreprocessTransparentMenu::class)
    ->preprocessHtml($variables);
}

/**
 * Implements hook_entity_type_alter().
 */
function dckyiv_core_entity_type_alter(array &$entity_types) {
  foreach ($entity_types as $entity_type)
  {
    $constraints = $entity_type->getConstraints();
    unset($constraints['EntityUntranslatableFields']);
    $entity_type->setConstraints($constraints);
  }
}
