pipeline {
    agent { docker { image 'php' } }
    stages {
        stage('build') {
            steps {
            echo "Scripted block"
            sh 'php --version'
            script {
            	php --version
            }
            }
        }
    }
}
