pipeline {
    agent {
        docker 'docksal/ci-agent:php'
    }
    stages {
        stage("CI-Agent") {
            steps {
                sh 'source build-env'
                sh 'printenv'
            }
        }
    }
}
