pipeline {
    agent {
        docker 'docksal/ci-agent:php'
    }
    stages {
        stage("CI-Agent") {
            steps {
                script {
                    source build-env
                }
            }
        }
    }
}
