#!/bin/bash

## DOOR3 Docksal package, v1.0
##
## Run Gulp in the theme folder
##
## Usage: fin phpcs <settings and path>

FILE="$1"

cd "${PROJECT_ROOT}"
fin run phpcs \
    --standard=Drupal,DrupalPractice -s \
    --colors \
    --extensions="php,module,inc,install,test,profile,theme" \
    --ignore="*.features.*,*.pages*.inc" \
    --report-code \
    $FILE
