#!/bin/bash

# Usage: fin phpcbf <settings and path>

FILE="$1"

cd "${PROJECT_ROOT}"
fin run phpcbf \
    --standard=vendor/drupal/coder/coder_sniffer/Drupal,vendor/drupal/coder/coder_sniffer/DrupalPractice -s \
    --colors \
    --extensions="php,module,inc,install,test,profile,theme,css,info,txt,md,yml" \
    --ignore="*.features.*,*.pages*.inc,*dist/assets/*,*fonts/icomoon*,*fonts/font-proxima-nova-scss*" \
    --report-code \
    $FILE
