#!/bin/bash

## DOOR3 Docksal package, v1.1
##
## @author Anton Trokhymenko antroxim@gmail.com
##
## Docksal custom command rebuild script
## Syncs DB from Pantheon environment, @see PANTHEON_ENV setting below
## Runs composer, drush cim, drush updb, drush cr
## Builds theme @see scripts/build_theme.sh
##
## TODO: Add ability to force new Pantheon backup to be create for latest DB sync
##
## Usage: fin rebuild

#Paths and environment settings
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
MAIN_THEME_PATH="${DOCROOT_PATH}/themes/custom/dckyiv"

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Show some art
clear
cat "${PROJECT_ROOT}/.docksal/assets/ascii.txt"

# Running composer
echo-yellow "Running composer install"
cd $PROJECT_ROOT
fin composer install --no-ansi --no-dev --no-interaction --optimize-autoloader --no-progress --prefer-dist --ignore-platform-reqs
echo-green "Done.\n"

# Database import
echo-yellow "Importing..."
fin db import $PROJECT_ROOT/db/database.sql --db-user=user --db-password=user
echo

# Running Drush commands
echo-yellow "Running drush cim, drush updb, drush cr"
cd $DOCROOT_PATH
fin drush cr
fin drush updb -y
fin drush cim -y
fin drush cr
#fin drush en stage_file_proxy -y
#fin drush config-set stage_file_proxy.settings origin "https://drupalcampkyiv.org"
#fin drush en devel -y
echo-green "Done.\n"

# Removing package-lock.json.
echo-yellow "Removing package-lock.json..."
rm -f $MAIN_THEME_PATH/package-lock.json
echo-green "Done."
echo

# revert node to version 8
fin exec nvm install 8.11.3
fin exec nvm alias default 8.11.3

# Building theme.
echo-yellow "Running gulp tasks in theme ${MAIN_THEME}"
fin gulp build

echo-green " <<<<<<< Rebuild is complete >>>>>>> "
echo
echo-green " Welcome to: http://dckyiv.docksal "
echo
